---

plugins:
  - babel
  - import
  - jest
  - prettier

env:
  browser: true
  es6: true
  jest: true
  node: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'prettier'

rules:
  prettier/prettier: error
  import/extensions: 0
